# Generated by Django 2.1 on 2019-05-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wastara_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='location',
            field=models.CharField(default='Morogoro', max_length=50),
        ),
    ]
